# Generated by Django 3.2.7 on 2021-11-05 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profesiones', '0001_initial'),
        ('NivelEstudios', '0001_initial'),
        ('Solicitud', '0002_auto_20211029_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='disponibilidad_cambioresidencia',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='disponibilidad_viajar',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='educacion_minima',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='profesion',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='nivelestudios_idnivelestudios',
            field=models.ForeignKey(db_column='NivelEstudios_idNivelEstudios', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NivelEstudios.nivelestudios'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='posibilidadcambioresidencia',
            field=models.CharField(blank=True, db_column='posibilidadCambioResidencia', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='posibilidadviajar',
            field=models.CharField(blank=True, db_column='posibilidadViajar', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='profesiones_idprofesiones',
            field=models.ForeignKey(db_column='Profesiones_idProfesiones', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Profesiones.profesiones'),
        ),
    ]
