# Generated by Django 3.2.7 on 2021-10-04 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitud', '0003_auto_20211001_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='empresa_idempresa',
            new_name='representante_idempresa',
        ),
    ]
