# Generated by Django 3.2.7 on 2022-01-04 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DuracionPaquetes', '0001_initial'),
        ('Paquetepago', '0003_auto_20211220_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquetepago',
            name='duracion',
        ),
        migrations.AddField(
            model_name='paquetepago',
            name='duracionpaquetes_idduracionpaquetes',
            field=models.ForeignKey(db_column='DuracionPaquetes_idDuracionPaquetes', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='DuracionPaquetes.duracionpaquetes'),
        ),
    ]
