# Generated by Django 3.2.7 on 2021-11-11 01:41

import applications.SugerenciaEmpresa.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugerenciaEmpresa',
            fields=[
                ('idsugerenciaempresa', models.AutoField(db_column='idSugerenciaEmpresa', primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=450, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=applications.SugerenciaEmpresa.models.nameFile)),
                ('empresa_idempresa', models.ForeignKey(db_column='Empresa_idEmpresa', on_delete=django.db.models.deletion.DO_NOTHING, to='Empresa.empresa')),
            ],
            options={
                'db_table': 'sugerenciaEmpresa',
            },
        ),
    ]
