# Generated by Django 3.2.7 on 2021-12-16 01:12

import applications.Aspirante.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EstadoAspirantes', '0001_initial'),
        ('Profesiones', '0001_initial'),
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('idaspirante', models.AutoField(db_column='idAspirante', primary_key=True, serialize=False)),
                ('numerohijos', models.IntegerField(blank=True, db_column='numeroHijos', null=True)),
                ('salarioMinimoAceptado', models.IntegerField(blank=True, db_column='salarioMinimoAceptado', null=True)),
                ('descripcionPerfilProfesional', models.CharField(blank=True, db_column='descripcionPerfilProfesional', max_length=100, null=True)),
                ('videopresentacion', models.FileField(blank=True, null=True, upload_to=applications.Aspirante.models.nameFile)),
                ('aniosexperiencia', models.IntegerField(blank=True, db_column='aniosExperiencia', null=True)),
                ('fechanacimiento', models.DateField(blank=True, db_column='fechaNacimiento', null=True)),
                ('posibilidadviajar', models.CharField(blank=True, db_column='posibilidadViajar', max_length=5, null=True)),
                ('posibilidadcambioresidencia', models.CharField(blank=True, db_column='posibilidadCambioResidencia', max_length=5, null=True)),
                ('idiomas', models.CharField(blank=True, db_column='idiomas', max_length=500, null=True)),
                ('estadoaspirantes_idestadoaspirantes', models.ForeignKey(db_column='estadoaspirantes_idestadoaspirantes', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='EstadoAspirantes.estadoaspirantes')),
                ('profesiones_idprofesiones', models.ForeignKey(db_column='Profesiones_idProfesiones', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Profesiones.profesiones')),
                ('usuario_idusuario', models.ForeignKey(db_column='usuario_idusuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Usuario.usuario')),
            ],
            options={
                'db_table': 'aspirante',
            },
        ),
    ]
