# Generated by Django 3.2.7 on 2021-10-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aspirante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirante',
            name='posibilidadviajar',
            field=models.CharField(blank=True, db_column='posibilidadViajar', max_length=100, null=True),
        ),
    ]
