# Generated by Django 3.2.7 on 2021-10-29 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estado', '0001_initial'),
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estado_idestado',
            field=models.ForeignKey(db_column='estado_idestado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Estado.estado'),
        ),
    ]
