# Generated by Django 3.2.6 on 2021-09-27 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Actividadeconomica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividadeconomica',
            options={'verbose_name': 'Actividadeconomica', 'verbose_name_plural': 'Actividadeconomicas'},
        ),
    ]
